### PR TITLE
Improve readability, style, and organization

### PR DESCRIPTION
**Pull request by dhimmel**
This pull request modifies most of the codebase, but the core functionality is the same besides:

1. only a single TSV is now exported
2. output is now in the `output` directory. The "example" output will get overwritten when a user reruns
3. date is not appended to the output path. Based on how you want to move this repo forward, different options for storing dates will exist.

### CODE REVIEW

**Comment by dhimmel** [comment]
https://github.com/rossmounce/checkmydois/pull/9/commits/6cab1d7cd29bb762a42df685123c2f3babe78ec4 enables specifying your own ORCID by argument or environment variable to address https://github.com/rossmounce/checkmydois/issues/5. @peterjc feel free to review.

**Comment by peterjc** [comment]
You'd need to update the ``.gitignore`` file too as the output filenames gave changed.

**Comment by dhimmel** [comment]
@peterjc I removed the old output file names from the ignores.

The new file for output (`output/works.tsv`) is intentionally not ignored as it takes the place of example-output.

I'm not sure this implementation is the best for the long term, but I also think it's not clear exactly how we want to store data.

Happy to change this if you have suggestions.

**Comment by peterjc** [comment]
Personally I would have the ``.gitignore`` exclude the output files, and any input/configuration files - and have this repository only track the code.

I was picturing putting the ORCID in a TravisCI environment variable so that you wouldn't need to change the contents of the repository at all to use this (see #5 and #8).

Another approach is to split the GitHub repository for the script (i.e. the code) and the GitHub repository for the personal DOI checker (i.e. the configuration) in two - and have the later install the latest version of the former (either direct from git or via CRAN)?

There are many options here - and what is best really depends on the intended use cases - including if it would be mainly locally run via cron, or online via TravisCI or otherwise?

**Comment by dhimmel** [comment]
> Personally I would have the .gitignore exclude the output files

@peterjc I think it's good to have a single output file, so whenever a file changes the output format, it's visible in the diff.

> I was picturing putting the ORCID in a TravisCI environment variable so that you wouldn't need to change the contents of the repository at all to use this

Agree, I implemented the environment variable method. However, currently if you run it on a DOI other than Ross's, your local `git status` will show changes for `output/works.tsv`. I don't think that's a huge issue, but there are alternatives:

1. the exported file would be of the format `0000-0002-3520-2046.tsv` (researcher specific). All other IDs in the `export` directory besides @rossmounce's would be ignored.
2. `checkmydois.R` would by default write `works.tsv` to stdout and there would be an `--output-file` option to specify a file to save to.

> There are many options here - and what is best really depends on the intended use cases - including if it would be mainly locally run via cron, or online via TravisCI or otherwise?

Agree, my inclination is to allow some data into to the repo, until it's clear how the project should evolve. @rossmounce have you had a chance to look at this PR?

**Comment by rossmounce** [comment]
full disclosure: I haven't really checked this PR but I'm going to accept it any way :)

**Pull request merged**
